package com.faefluffkrist.trimworks.config;

public final class BuiltInBonusesConfig {
    public boolean enabled = true;
    public boolean wardSwiftSneak = true;
    public boolean wardDarknessImmunity = true;
    public boolean wardAncientCitySpeed = true;
    public boolean silenceWardenNeutrality = true;
    public boolean silenceSculkSpeed = true;
    public boolean silenceSpectralMark = true;
    public boolean tideDolphinsGrace = true;
    public boolean boltMeleeKnockback = true;
    public boolean boltProjectileDeflection = true;
    public double boltProjectileDeflectionChance = 0.25D;
    public boolean coastConduitPower = true;
    public boolean sentryIllagerNeutrality = true;
    public boolean sentryTheftProvocation = true;
    public boolean sentryTheftWarning = true;
    public boolean sentryTheftSnitching = true;
    public boolean sentryGroupRetaliation = true;
    public boolean sentryEvokerWarning = true;
    public boolean sentryFriendsAndFoesNeutrality = true;
    public boolean sentryTakesAPillageNeutrality = true;
    public boolean vexNeutrality = true;
    public boolean duneTerrainSpeed = true;
    public boolean wildTerrainSpeed = true;
    public boolean eyeTerrainSpeed = true;
    public boolean eyeEndermanGazeImmunity = true;
    public boolean snoutBruteHoglinNeutrality = true;
    public boolean ribWitherImmunity = true;
    public double wardSneakTwoPieces = 0.15D;
    public double wardSneakFourPieces = 0.30D;
    public int wardSpeedLevel = 1;
    public int silenceSpeedLevel = 1;
    public int silenceMarkTicks = 200;
    public int tideGraceLevel = 1;
    public int coastConduitLevel = 1;
    public int duneSpeedLevel = 2;
    public int wildSpeedLevel = 2;
    public int eyeSpeedLevel = 2;
    public double boltKnockbackTwoPieces = 0.45D;
    public double boltKnockbackFourPieces = 0.90D;
    public java.util.Map<String, java.util.List<BonusRule>> extraBonuses = new java.util.LinkedHashMap<>();
}
